name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++-14 lcov libgtk-3-dev libayatana-appindicator3-dev libhidapi-dev libudev-dev libvulkan-dev vulkan-tools

    - name: Configure CMake
      run: |
        git submodule update --init --recursive
        export CXX=/usr/bin/g++-14
        cmake -DCMAKE_BUILD_TYPE=Release .

    - name: Build project
      run: make runTests

    - name: Run tests
      run: ./tests/runTests

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: ./tt_riing_quad_fan_control
